#!/usr/bin/env node
// Generates the Pine-comparison variants of the modules whose logic runs as Pine script
// in the indicator (F-007): every < <= > >= === !== becomes lt/le/gt/ge/eq/ne from
// ../pine-cmp.mjs; nothing else changes. Loose == / != (only used against null) stay.
// The sources stay verbatim (ZE2); the measurement pipeline imports the generated files.
//   node engine/pinecmp/build.mjs          (dev-time: needs the acorn parser)
// Test PC-G checks that every generated file records the sha256 of its current source.
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, relative, resolve, basename } from 'node:path';
import { readdirSync } from 'node:fs';

const here = dirname(fileURLToPath(import.meta.url));
const lab = resolve(here, '../..');

// source (relative to the lab) → generated name
export const SOURCES = [
  ['engine/zone-engine.mjs', 'zone-engine.mjs'],
  ['engine/sensors.mjs', 'sensors.mjs'],
  ['engine/consumer.mjs', 'consumer.mjs'],
  ['gtg-engine/reference/obstacle.mjs', 'obstacle.mjs'],
];
const OPS = { '<': 'lt', '<=': 'le', '>': 'gt', '>=': 'ge', '===': 'eq', '!==': 'ne' };

export const sha256 = (s) => createHash('sha256').update(s).digest('hex');
export const headerOf = (src, text) => [
  `// GENERATED by engine/pinecmp/build.mjs from ${src} — do not edit (FAILURE_LOG F-007).`,
  `// source sha256: ${sha256(text)}`,
  '// Every float comparison follows Pine semantics (../pine-cmp.mjs); nothing else differs.',
].join('\n');

async function loadAcorn() {
  try { return await import('acorn'); } catch { /* fall through to the monorepo store */ }
  const store = resolve(lab, '../../node_modules/.pnpm');
  const dir = readdirSync(store).find((d) => /^acorn@\d/.test(d));
  if (!dir) throw new Error('acorn parser not found (dev-time dependency of the generator only)');
  return import(pathToFileURL(resolve(store, dir, 'node_modules/acorn/dist/acorn.mjs')).href);
}

function isNode(x) { return x && typeof x === 'object' && typeof x.type === 'string' && typeof x.start === 'number'; }

function childrenOf(node) {
  const out = [];
  for (const k of Object.keys(node)) {
    const v = node[k];
    if (Array.isArray(v)) v.forEach((c) => isNode(c) && out.push(c));
    else if (isNode(v)) out.push(v);
  }
  return out.sort((a, b) => a.start - b.start);
}

export function transform(text, acorn, rewriteImport) {
  const ast = acorn.parse(text, { ecmaVersion: 'latest', sourceType: 'module' });
  let count = 0;
  const render = (node) => {
    if (node.type === 'BinaryExpression' && OPS[node.operator]) {
      count++;
      return `${OPS[node.operator]}(${render(node.left)}, ${render(node.right)})`;
    }
    if (node.type === 'ImportDeclaration') {
      const src = rewriteImport(node.source.value);
      return text.slice(node.start, node.source.start) + JSON.stringify(src).replace(/"/g, "'") + text.slice(node.source.end, node.end);
    }
    let s = '', pos = node.start;
    for (const c of childrenOf(node)) {
      if (c.start < pos) continue; // shorthand property: key and value share one range
      s += text.slice(pos, c.start) + render(c); pos = c.end;
    }
    return s + text.slice(pos, node.end);
  };
  const body = text.slice(0, ast.start) + render(ast) + text.slice(ast.end);
  return { body, count };
}

export async function build({ write = true } = {}) {
  const acorn = await loadAcorn();
  const generated = new Map(SOURCES.map(([s, g]) => [resolve(lab, s), g]));
  const out = [];
  for (const [src, gen] of SOURCES) {
    const abs = resolve(lab, src);
    const text = readFileSync(abs, 'utf8');
    const rewrite = (spec) => {
      if (!spec.startsWith('.')) return spec;
      const target = resolve(dirname(abs), spec);
      if (generated.has(target)) return `./${generated.get(target)}`;
      const r = relative(here, target).replace(/\\/g, '/');
      return r.startsWith('.') ? r : `./${r}`;
    };
    const { body, count } = transform(text, acorn, rewrite);
    const file = `${headerOf(src, text)}\nimport { eq, ne, lt, gt, le, ge } from '../pine-cmp.mjs';\n${body}`;
    if (write) writeFileSync(resolve(here, gen), file);
    out.push({ src, gen: basename(gen), comparisons: count, file });
  }
  return out;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  for (const r of await build()) console.log(`${r.src} → pinecmp/${r.gen}: ${r.comparisons} comparisons`);
}
