// GENERATED by engine/pinecmp/build.mjs from engine/consumer.mjs — do not edit (FAILURE_LOG F-007).
// source sha256: 8de544802eeac0c2769daa0dc5debb74074298b38bfd73aa3d129274eb9978c0
// Every float comparison follows Pine semantics (../pine-cmp.mjs); nothing else differs.
import { eq, ne, lt, gt, le, ge } from '../pine-cmp.mjs';
// Sections 12 (slot adapter: displayQ), 13 (obstacle awareness) and 17 (the ten alerts)
// of gtg_navigator_v0.4.7.pine, one confirmed bar at a time.
import { strongObstacleStep, newObstacleLatch } from './obstacle.mjs';
import { INPUTS } from '../profiles.mjs';

// Pine 1497–1500: displayQ = min(100, gateQ + 4·maConf + 3·psychConf). psychConf needs
// syminfo.type == "crypto" (false for XAUUSD); includeMA200/includeMA1000 default true.
export function displayQOf(slot, ma200, ma1000, { isCrypto = false, close = NaN } = {}) {
  if (!slot.active) return slot.quality;
  const maConf = (ge(ma200, slot.lo) && le(ma200, slot.hi)) || (ge(ma1000, slot.lo) && le(ma1000, slot.hi));
  let psychConf = false;
  if (isCrypto) {
    const p = close;
    const step = ge(p, 100000) ? 10000 : ge(p, 50000) ? 5000 : ge(p, 10000) ? 1000 : ge(p, 1000) ? 500 : ge(p, 100) ? 50 : ge(p, 10) ? 5 : 1;
    psychConf = le(Math.ceil(slot.lo / step) * step, slot.hi);
  }
  return Math.min(100, slot.gateQ + (maConf ? 4 : 0) + (psychConf ? 3 : 0));
}

const zoneDistance = (lo, hi, c) => (lt(c, lo) ? lo - c : gt(c, hi) ? c - hi : 0.0);

export function newConsumerState() {
  return { latch: newObstacleLatch(), prevNoChase: false, prevSpeed: NaN, prevFuel: NaN, prevHeading: NaN };
}

// slots: [R1, R2, S1, S2] after this bar's write (quality = displayQ). ev: engine events.
// s: sensor values at this bar. Returns the consumer row and advances `st`.
export function consumerStep(st, bar, slots, ev, s, atrEng, I = INPUTS) {
  const [R1, R2, S1, S2] = slots;
  const c = bar.c;
  const lo = (x) => (x.active ? x.lo : NaN), hi = (x) => (x.active ? x.hi : NaN), q = (x) => (x.active ? x.quality : NaN);
  const mapDirectionSign = ne(s.tacticalSign, 0) ? s.tacticalSign : s.routeSign;
  const containR = R1.active && R1.containing, containS = S1.active && S1.containing;
  const res1Dist = R1.active ? zoneDistance(R1.lo, R1.hi, c) / atrEng : 99.0;
  const sup1Dist = S1.active ? zoneDistance(S1.lo, S1.hi, c) / atrEng : 99.0;
  const primaryUp = containR ? true : containS ? false : (gt(mapDirectionSign, 0) || (eq(mapDirectionSign, 0) && le(res1Dist, sup1Dist)));
  const d1 = primaryUp ? R1 : S1;
  const dest1Low = lo(d1), dest1High = hi(d1), dest1Strength = q(d1);
  const obstacleAvailable = !Number.isNaN(dest1Low) && !Number.isNaN(dest1High);
  const nearestObstacleAtr = !Number.isNaN(dest1Low) ? zoneDistance(dest1Low, dest1High, c) / atrEng : NaN;
  const nearestObstacleStrong = !Number.isNaN(dest1Strength) && ge(dest1Strength, I.strongQ);
  // roleType text is "مقاومة • …" for R slots and "دعم • …" for S slots; no source/tag word
  // contains the other side's keywords, so the role is the slot side.
  const obstacleRole = !obstacleAvailable ? 0 : primaryUp ? 1 : -1;
  const priceInsideObstacle = obstacleAvailable && ge(c, dest1Low) && le(c, dest1High);
  const candleTouchesObstacle = obstacleAvailable && ge(bar.h, dest1Low) && le(bar.l, dest1High);
  const obstacleNear = obstacleAvailable && !Number.isNaN(nearestObstacleAtr) && le(nearestObstacleAtr, I.nearObstacleAtr);

  const fuelNotSupportingChase = lt(s.fuelAcceleration, -3) || lt(s.fuelScore, I.noChaseFuelMax) || lt(s.fuelScore + 18, s.speedScore);
  const speedHotForChase = ge(s.speedScore, Math.max(60.0, I.speedFastThreshold - 10.0)) || ge(s.instantSpeedScore, I.speedExtremeThreshold);
  const obstacleEngagedForChase = obstacleAvailable && (le(nearestObstacleAtr, I.noChaseAtr) || priceInsideObstacle || candleTouchesObstacle);
  const noChaseUp = gt(s.tacticalSign, 0) && eq(obstacleRole, 1) && obstacleEngagedForChase && speedHotForChase && fuelNotSupportingChase;
  const noChaseDown = lt(s.tacticalSign, 0) && eq(obstacleRole, -1) && obstacleEngagedForChase && speedHotForChase && fuelNotSupportingChase;
  const noChase = noChaseUp || noChaseDown;

  // 17. alerts (every lab bar is a confirmed bar)
  const speedBurst = ge(s.speedScore, I.speedExtremeThreshold) && lt(st.prevSpeed, I.speedExtremeThreshold);
  const fuelSurge = ge(s.fuelScore, I.fuelHighThreshold) && lt(st.prevFuel, I.fuelHighThreshold);
  const headingUp = gt(s.headingScore, I.headingClearThreshold) && le(st.prevHeading, I.headingClearThreshold);
  const headingDown = lt(s.headingScore, -I.headingClearThreshold) && ge(st.prevHeading, -I.headingClearThreshold);
  const dest1EntryKeys = primaryUp ? R1.entryKeys : S1.entryKeys;
  const latchBefore = st.latch;
  const obs = { confirmed: true, available: obstacleAvailable, strength: Number.isNaN(dest1Strength) ? null : dest1Strength,
    distAtr: Number.isNaN(nearestObstacleAtr) ? null : nearestObstacleAtr, entryKeys: dest1EntryKeys };
  const so = strongObstacleStep(latchBefore, obs, { strongQ: I.strongQ, nearObstacleAtr: I.nearObstacleAtr });
  const strongObsNow = so.latch.state;
  const strongObsSame = latchBefore.keys.some((k) => dest1EntryKeys.includes(k));
  const nearStrongObstacle = so.event;
  const noChaseEvent = noChase && !st.prevNoChase;
  const obstacleBreakEvent = ev.breakingUp || ev.breakingDn;
  const obstacleRejectEvent = ev.rejectR || ev.rejectS;
  const breakAcceptedEvent = ev.acceptedUp || ev.acceptedDn;
  const flipConfirmedEvent = ev.flipConfirmed;
  const engineEventBits = (ev.breakingUp ? 1 : 0) + (ev.breakingDn ? 2 : 0) + (ev.acceptedUp ? 4 : 0) + (ev.acceptedDn ? 8 : 0)
    + (ev.rejectR ? 16 : 0) + (ev.rejectS ? 32 : 0) + (ev.flipConfirmed ? 64 : 0);
  const alertBits = (speedBurst ? 1 : 0) + (fuelSurge ? 2 : 0) + (headingUp ? 4 : 0) + (headingDown ? 8 : 0) + (nearStrongObstacle ? 16 : 0)
    + (noChaseEvent ? 32 : 0) + (obstacleBreakEvent ? 64 : 0) + (obstacleRejectEvent ? 128 : 0) + (breakAcceptedEvent ? 256 : 0) + (flipConfirmedEvent ? 512 : 0);
  const obsState = (strongObsNow ? 1 : 0) + (latchBefore.state ? 2 : 0) + (strongObsSame ? 4 : 0) + (nearStrongObstacle ? 8 : 0);

  st.latch = so.latch;
  st.prevNoChase = noChase;
  st.prevSpeed = s.speedScore; st.prevFuel = s.fuelScore; st.prevHeading = s.headingScore;

  return {
    primaryUp, dest1Low, dest1High, dest1Strength, nearestObstacleAtr, nearestObstacleStrong, obstacleRole,
    priceInsideObstacle, candleTouchesObstacle, obstacleNear, noChaseUp, noChaseDown, noChase,
    speedBurst, fuelSurge, headingUp, headingDown, nearStrongObstacle, noChaseEvent,
    obstacleBreakEvent, obstacleRejectEvent, breakAcceptedEvent, flipConfirmedEvent,
    eventBits: engineEventBits + alertBits * 128, alertBits, engineEventBits, obsState,
    latch: { state: so.latch.state, keys: so.latch.keys.slice() },
  };
}
